### ISSUE TITLE
problems during training

### ISSUE THREAD

**Issue by yuqikong** [LeeKeyu/sarl_star#4]
Hello, I'm very impressed with your work. I also want to ask a question, does the training run train.py? I'm curious if there will be static obstacles in the training scene?

**Comment by LeeKeyu** [comment]
Yes, please refer to the steps shown in the Readme.md to conduct training in the simulation. In this work, static obstacles are not included in the training and are only handled during the deployment of the SARL* algorithm. But feel free to modify the simulation environment to add them.
